name: CI Workflow  

on:
  push:
    branches:
      - main  # push to the main branch
  pull_request:
    branches:
      - main  # pull requests to the main branch

jobs:
  # Job for building and testing on Ubuntu
  build_ubuntu:
    runs-on: ubuntu-latest 

    steps:
    # Step to checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to set up the .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0' 

    # Step to restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step to build the project
    - name: Build project
      run: dotnet build --configuration Release

    # Step to run tests
    - name: Run tests
      run: dotnet test --configuration Release

  # Job for building and testing on Windows
  build_windows:
    runs-on: windows-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release
