name: CI Workflow  

on:
  push:
    branches:
      - main  # push to the main branch
  pull_request:
    branches:
      - main  # pull requests to the main branch

jobs:
  # Job for building and testing on Windows
  build_windows:
    runs-on: windows-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release
      
  # Job for building and testing on Windows
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    # Set working directory to 'SmartCrop' 
    - name: Set working directory to SmartCrop
      run: cd SmartCrop
    
    # Restore dependencies for the entire solution 
    - name: Restore dependencies for SmartCrop.sln
      run: dotnet restore SmartCrop.sln --verbosity detailed # Using detailed verbosity to troubleshoot why this is failing (in case it fails again) 

    # Build project 
    - name: Build project using SmartCrop.sln
      run: dotnet build SmartCrop.sln --configuration Release

    # Run tests
    - name: Run tests for SmartCrop
      run: dotnet test SmartCrop.sln --configuration Release

 
