name: CI Workflow  

on:
  push:
    branches:
      - main  # push to the main branch
  pull_request:
    branches:
      - main  # pull requests to the main branch

jobs:
  # Job for building and testing on Windows
  build_windows:
    runs-on: windows-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    - name: Set API key from secrets
        env:
          OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
        run: |
          echo "Retrieving OpenWeatherMap API Key from Github secrets"
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release
      
  # Job for building and testing on macOS
  build_macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release

 
 
