# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - SmartCrop

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build and Publish SmartCrop Solution
        run: |
          # Build and publish the solution to ensure the output directories exist
          dotnet build SmartCrop.sln -c Release
          dotnet publish SmartCrop.sln -c Release -o D:/a/CropHealth/SmartCrop/Smartcrop.Shared/bin/Release/net8.0/
          dotnet publish SmartCrop.sln -c Release -o D:/a/CropHealth/SmartCrop/SmartCrop.Client/bin/Release/net8.0/
          dotnet publish SmartCrop.sln -c Release -o D:/a/CropHealth/SmartCrop/SmartCrop/bin/Release/net8.0/

      - name: Create directories if they don't exist
        run: |
          # Ensure the necessary directories exist before uploading artifacts
          mkdir -p D:/a/CropHealth/SmartCrop/Smartcrop.Shared/bin/Release/net8.0/
          mkdir -p D:/a/CropHealth/SmartCrop/SmartCrop.Client/bin/Release/net8.0/
          mkdir -p D:/a/CropHealth/SmartCrop/SmartCrop/bin/Release/net8.0/

      - name: List build output files
        run: |
          echo "Contents of SmartCrop.Shared directory:"
          dir D:/a/CropHealth/SmartCrop/Smartcrop.Shared/bin/Release/net8.0/
          echo "Contents of SmartCrop.Client directory:"
          dir D:/a/CropHealth/SmartCrop/SmartCrop.Client/bin/Release/net8.0/
          echo "Contents of SmartCrop directory:"
          dir D:/a/CropHealth/SmartCrop/SmartCrop/bin/Release/net8.0/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: |
            D:/a/CropHealth/SmartCrop/Smartcrop.Shared/bin/Release/net8.0/Smartcrop.Shared.dll
            D:/a/CropHealth/SmartCrop/SmartCrop.Client/bin/Release/net8.0/SmartCrop.Client.dll
            D:/a/CropHealth/SmartCrop/SmartCrop.Client/bin/Release/net8.0/wwwroot/**
            D:/a/CropHealth/SmartCrop/SmartCrop/bin/Release/net8.0/SmartCrop.dll

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Development'  # Changed to 'Development' for the dev environment
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SmartCrop'  # Ensure this matches your development app name
          slot-name: 'Development'  # Changed to 'Development' for the dev slot
          package: ${{ github.workspace }}/ASP-app
